### ISSUE TITLE
Request path for withdraw is incorrect.

### ISSUE THREAD

**Issue by britecoin** [AndrewBarba/bittrex-node#2]
Request path for withdraw is incorrect. Line 214 in bittrex-client.js

return this.request('get', '/account/getdepositaddress', { params })

**Comment by AndrewBarba** [comment]
Thanks! I'll get that fixed shortly

**Comment by AndrewBarba** [comment]
Yup that makes sense, fixing that too

**Comment by AndrewBarba** [comment]
Ok both should be fixed: https://github.com/AndrewBarba/bittrex-node/releases/tag/1.0.3
