### ISSUE TITLE
getopenorders

### ISSUE THREAD

**Issue by mkolbusz** [AndrewBarba/bittrex-node#4]
Shouldn't this method `openOrders(market)` have parameter `market` optional to get all open orders in one request? The API endpoint `/market/getopenorders` has it optional.

@AndrewBarba maybe implementation without Error raising:
```
async openOrders(market) {
    // if (!market) throw new Error('market is required')
    let params = { market }
    let results = await this.request('get', '/market/getopenorders', { params })
    return this.parseDates(results, ['Opened'])
  }
```

**Comment by AndrewBarba** [comment]
Yup that definitely makes sense. I’m traveling the next few days, but if you can submit a PR I’ll approve and merge it

**Comment by mkolbusz** [comment]
Thanks :) I created the PR
