### ISSUE TITLE
order() doesn't parse Closed date

### ISSUE THREAD

**Issue by CherryDT** [AndrewBarba/bittrex-node#8]
Now that #7 is fixed, a second issue surfaces that was hidden before: it should parse both `Opened` and `Closed` and not just `Opened`.

![image](https://user-images.githubusercontent.com/6010463/59054411-4d9e3380-889c-11e9-820a-6c0148f0baae.png)

**Comment by AndrewBarba** [comment]
Fixed! https://github.com/AndrewBarba/bittrex-node/releases/tag/1.2.1
